services:
  api:
    build: .
    volumes:
      - type: bind
        source: ./.env
        target: /opt/app/accountStatusLA/.env
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/accountStatusLA
      PORT: 3001
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
